version: "3.9"

networks:
  back:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:15.2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/incident_volume:/docker-entrypoint-initdb.d
      - ~/incident_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back

  backend:
    build: ./
    restart: always
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - back
    depends_on:
      - postgres