// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: incidents.sql

package db

import (
	"context"
)

const getAllIncidents = `-- name: GetAllIncidents :many
SELECT id, registration_date, summary, incident_type FROM incidents
`

func (q *Queries) GetAllIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, getAllIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationDate,
			&i.Summary,
			&i.IncidentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
