// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"

	"github.com/gofrs/uuid"
	"github.com/guregu/null"
)

type Decision struct {
	ID           uuid.UUID   `json:"id"`
	IncidentID   uuid.UUID   `json:"incident_id"`
	DecisionType null.String `json:"decision_type"`
}

type Incident struct {
	ID               uuid.UUID   `json:"id"`
	RegistrationDate time.Time   `json:"registration_date"`
	Summary          null.String `json:"summary"`
	IncidentType     null.String `json:"incident_type"`
}

type IncidentIndividualLink struct {
	ID           uuid.UUID   `json:"id"`
	IncidentID   uuid.UUID   `json:"incident_id"`
	IndividualID uuid.UUID   `json:"individual_id"`
	Role         null.String `json:"role"`
}

type Individual struct {
	ID                   uuid.UUID   `json:"id"`
	FirstName            null.String `json:"first_name"`
	LastName             null.String `json:"last_name"`
	MiddleName           null.String `json:"middle_name"`
	Address              null.String `json:"address"`
	CriminalRecordsCount null.Int    `json:"criminal_records_count"`
}

type Token struct {
	ID        uuid.UUID `json:"id"`
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt null.Time `json:"created_at"`
	ExpiresAt null.Time `json:"expires_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      int32     `json:"role"`
	CreatedAt null.Time `json:"created_at"`
}
