// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
	"github.com/guregu/null"
)

type Decision struct {
	ID           uuid.UUID      `json:"id"`
	IncidentID   uuid.UUID      `json:"incident_id"`
	DecisionType sql.NullString `json:"decision_type"`
}

type Incident struct {
	ID               uuid.UUID      `json:"id"`
	RegistrationDate time.Time      `json:"registration_date"`
	Summary          sql.NullString `json:"summary"`
	IncidentType     sql.NullString `json:"incident_type"`
}

type IncidentIndividualLink struct {
	ID           uuid.UUID      `json:"id"`
	IncidentID   uuid.UUID      `json:"incident_id"`
	IndividualID uuid.UUID      `json:"individual_id"`
	Role         sql.NullString `json:"role"`
}

type Individual struct {
	ID                   uuid.UUID      `json:"id"`
	FirstName            sql.NullString `json:"first_name"`
	LastName             sql.NullString `json:"last_name"`
	MiddleName           sql.NullString `json:"middle_name"`
	Address              sql.NullString `json:"address"`
	CriminalRecordsCount null.Int       `json:"criminal_records_count"`
}
