// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	GetAllIncidents(ctx context.Context) ([]Incident, error)
}

var _ Querier = (*Queries)(nil)
